# Generated by Django 3.1.1 on 2020-09-13 22:20

import apps.artists.models
from apps.artists.models import Social
from django.db import migrations, models
import django.db.models.deletion


def seed(apps, schema_editor):
    social_networks = ["Amazon Music", "Apple Music", "Beatport", "Deezer", "Facebook", "Google Music", "Instagram", "Itunes", "Juno", "Qobuz", "Snapchat", "Soundcloud", "Spotify", "Twitter", "Youtube"]
    for network in social_networks:
        Social.objects.get_or_create(name=network)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.artists.models.define_bio_image)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to=apps.artists.models.define_social_image)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.artists.models.define_song_image)),
                ('featured_name', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SongSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_social_network', to='artists.social')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_socials', to='artists.song')),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('french', models.TextField(blank=True)),
                ('english', models.TextField(blank=True)),
                ('german', models.TextField(blank=True)),
                ('spanish', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='artists.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_socials', to='artists.artist')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_social_network', to='artists.social')),
            ],
        ),
        migrations.RunPython(seed),
    ]
