# Generated by Django 3.0.7 on 2020-09-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsocial',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='songsocial',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='artists.Song'),
        ),
    ]
