# Generated by Django 3.1.1 on 2020-09-26 19:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20200919_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='english',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='biography',
            name='french',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='biography',
            name='german',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='biography',
            name='spanish',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
