# Generated by Django 3.1.4 on 2020-12-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20200926_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biography',
            old_name='english',
            new_name='de',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='french',
            new_name='en',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='german',
            new_name='es',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='spanish',
            new_name='fr',
        ),
    ]
