# Generated by Django 3.1.4 on 2020-12-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20201208_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='artists.artist'),
        ),
    ]
